version: "3"
services:
  # BACKEND API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start -- -L
    working_dir: /usr/src/smart-brain-api
    environment:
      DATABASE_URL: eyal:secret@postgres:5432/smart-brain-docker
      REDIS_URL: redis://redis:6379
      POSTGRES_USER: eyal
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3001
      CLARIFAI_API_KEY: f9d70547a2264d97a31db187a63a6976
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: eyal
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5431:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
